# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GL8GszBPV6RN4gt8Ud3DhDcUDfbED1hG
"""

# app.py

import streamlit as st
import joblib
import pandas as pd

MODEL_PATH = "model.joblib"

# ============== Load Model ==============
@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)

model = load_model()

# Ambil schema fitur dari model
numerical = model.feature_schema["numerical"]
categorical = model.feature_schema["categorical"]
feature_names = numerical + categorical

st.set_page_config(page_title="Telco Churn Predictor", layout="centered")
st.title("📡 Telco Customer Churn - Logistic Regression Predictor")

# ============== Form Input ==============
st.header("Input Fitur Pelanggan")

input_data = {}

with st.form("predict_form"):
    cols = st.columns(2)

    for i, feat in enumerate(feature_names):
        col = cols[i % 2]
        if feat in numerical:
            input_data[feat] = col.number_input(feat, value=0.0)
        else:
            input_data[feat] = col.text_input(feat, value="")

    submitted = st.form_submit_button("Predict")

# ============== Prediksi ==============
if submitted:
    df = pd.DataFrame([input_data])

    proba = model.predict_proba(df)[0]
    pred = model.predict(df)[0]

    st.subheader("Hasil Prediksi")
    st.write(f"Prediksi Churn: **{'Yes' if pred == 1 else 'No'}**")

    st.write("Probabilitas:")
    st.write({"Tidak Churn": proba[0], "Churn": proba[1]})

    st.bar_chart(pd.Series(proba, index=["Tidak Churn", "Churn"]))